version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: online-food-delivery
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/online-food-delivery # todo setup remote postgres service
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}

