
FROM maven:3.8.4-openjdk-11 AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn package -DskipTests

FROM openjdk:11-jre-slim

WORKDIR /app

COPY --from=builder /app/target/your-project-name.jar ./app.jar

EXPOSE 8000

CMD ["java", "-jar", "app.jar"]